# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FireBase-Inflearn' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FireBase-Inflearn
  pod 'Firebase'
  pod 'FirebaseAnalytics'
  pod 'FirebaseAuth'
  pod 'FirebaseFirestore'
  pod 'FirebaseStorage'
end
